config/routes.rb
Rails.application.routes.draw do
  get 'calendar/show'

  get 'uploads/new'
  get 'uploads/create'
  get 'uploads/index'
  get 'dashboards/join'
  put 'dashboards/join'
  post 'dashboards/search'

  resources :uploads
  resources :events
  resources :news_feeds

  resources :dashboards do
    resources :news_feeds
    resources :events
  end

  resources :dashboards, shallow: true do
    resources :uploads
  end

  devise_for :users
  resource :users
  resource :calendar, only: [:show], controller: :calendar
  root 'user#home'

  get "/wyncode" => redirect("http://wyncode.co/")
  get "/about" => 'user#about'


end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :dashboard




end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_dashboard, only: [:new, :index]
  before_action :authenticate_user!

  # GET /events
  # GET /events.json



  def index
    @events = @dashboard.events
    #@events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = @dashboard.events.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @dashboard = Dashboard.find(params[:event][:dashboard_id])

    @event = @dashboard.events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def set_dashboard
        @dashboard = Dashboard.find(params[:dashboard_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :time, :end_time, :dashboard_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, class:"cabin" %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :date, class:"cabin" %><br>
    <%= f.text_field :date, id:"datepicker" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :start_time, class:"cabin" %><br>
    <%= f.time_select :time, {ampm: true, minute_step: 15} %>
  </div>
  <br>
  <div class="field">
    <%= f.label :end_time, class:"cabin" %><br>
    <%= f.time_select :end_time, {ampm: true, minute_step: 15} %>
  </div>

  <%= f.hidden_field :dashboard_id, value: @dashboard.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', event_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.date %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', 'events#new' %>

<%= link_to 'Dashboard', dashboards_path %>

app/views/events/new.html.erb
<div class="form_flexbox_container">
  <div class="form_top">

    <h1>New Event</h1>
    <%= render 'form' %>


</div>
</div>

app/views/events/show.html.erb
<div class="form_flexbox_container">
  <div class="user_form cabin">
    <p id="notice_new_event"><%= notice %></p>

    <div id="toggle">
      <p>
        <strong>Name:</strong>
        <%= @event.name %>
      </p>

      <p>
        <strong>Date:</strong>
        <%= @event.date %>
      </p>

      <p>
        <strong>Start Time:</strong>
        <%= @event.time.strftime("%H:%M") %>
      </p>

      <p>
        <strong>End Time:</strong>
        <%= @event.end_time.strftime("%H:%M") %>
      </p>

      <%= link_to 'Edit', edit_event_path(@event) %> |
      <%= link_to 'Back', dashboard_path(@event.dashboard) %> |
      <%= link_to 'Destroy', event_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
</div>