config/routes.rb
Rails.application.routes.draw do
  get 'calendar/show'

  get 'uploads/new'
  get 'uploads/create'
  get 'uploads/index'
  get 'dashboards/join'
  put 'dashboards/join'
  post 'dashboards/search'

  resources :uploads
  resources :events
  resources :news_feeds

  resources :dashboards do
    resources :news_feeds
    resources :events
  end

  resources :dashboards, shallow: true do
    resources :uploads
  end

  devise_for :users
  resource :users
  resource :calendar, only: [:show], controller: :calendar
  root 'user#home'

  get "/wyncode" => redirect("http://wyncode.co/")
  get "/about" => 'user#about'


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :dashboards
  has_many :dashboard_memberships, foreign_key: :member_id
  has_many :memberships, through: :dashboard_memberships, source: :dashboard

  # custom validation
  # not valid if dashboard_memberships has two of the same dashboard

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
  end

  def home
    render layout: 'home'
  end

  def about
  end

end

app/helpers/user_helper.rb
module UserHelper

end

app/views/user/_login.html.erb
<!-- LOG IN SECTION -->
<h2>Log in</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>

  <div>
    <%= link_to 'Log Out', '/sign_out' %>
  </div>
<% end %>

app/views/user/_new.html.erb
<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/user/about.html.erb
About Page!!

app/views/user/home.html.erb
<div class="center">
  <h1>Welcome To GroupBoard</h1>

  <%= link_to 'Log-In', new_user_session_path, class: "btn btn-off-white cabin" %>
  <%= link_to 'Sign-up', new_user_registration_path, class: "btn btn-off-blue cabin" %>
  <br>
</div>