config/routes.rb
Rails.application.routes.draw do
  get 'calendar/show'

  get 'uploads/new'
  get 'uploads/create'
  get 'uploads/index'
  get 'dashboards/join'
  put 'dashboards/join'
  post 'dashboards/search'

  resources :uploads
  resources :events
  resources :news_feeds

  resources :dashboards do
    resources :news_feeds
    resources :events
  end

  resources :dashboards, shallow: true do
    resources :uploads
  end

  devise_for :users
  resource :users
  resource :calendar, only: [:show], controller: :calendar
  root 'user#home'

  get "/wyncode" => redirect("http://wyncode.co/")
  get "/about" => 'user#about'


end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  belongs_to :user
  has_many :dashboard_memberships
  has_many :members, through: :dashboard_memberships
  has_many :uploads, dependent: :destroy
  has_many :news_feeds, dependent: :destroy
  has_many :events, dependent: :destroy

  validates :user, presence: true
  validates :token, uniqueness: true

  def find_or_create_member(user)
    if !members.include?(user)
      members << user
    end
  end

  def self.search(search)
    where("token LIKE ?", "%#{search}%")
  end

  # this is bad
  def set_user(user)
    self.user_id = user.id
  end

  def events_by_date
    events.group_by(&:date)
    # events.group_by{ |event| event.date }
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_dashboard, only: [:show, :edit, :update, :destroy]
  before_action :set_dashboards, only: [:join]
  before_action :authenticate_user!
  before_action :generate_token, only: [:create]
  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboards = Dashboard.all
  end

  def search
    @dashboard = Dashboard.find_by(token: params[:search])
    if @dashboard.nil?
      flash[:error] = "Sorry, that dashboard was not found."
      redirect_to dashboards_path
    else
      @dashboard.find_or_create_member(current_user)
      redirect_to @dashboard
    end
  end

  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
    @news_feed = NewsFeed.new
    @event = Event.new
    @upload = Upload.new
    # @news_feeds = NewsFeed.all
    @last_three = NewsFeed.items_for_dashboard(@dashboard)
    @uploads = Upload.all
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @events_by_date = @dashboard.events_by_date
  end

  # GET /dashboards/new
  def new
    @dashboard = Dashboard.new
  end

  # GET /dashboards/1/edit
  def edit
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    # render plain: params.to_json
    @dashboard = Dashboard.new(dashboard_params)
    @dashboard.set_user(current_user)
    @dashboard.token = @token

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard }
      else
        format.html { render :new }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboards/1
  # PATCH/PUT /dashboards/1.json
  def update
    respond_to do |format|
      if @dashboard.update(dashboard_params)
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard }
      else
        format.html { render :edit }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard.destroy
    respond_to do |format|
      format.html { redirect_to dashboards_url, notice: 'Dashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard
      @dashboard = Dashboard.find(params[:id])
    end

    def generate_token
      @token = SecureRandom.uuid
    end

    def set_dashboards
      @dashboards = Dashboard.all
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_params
      params.require(:dashboard).permit(:title, :token, :user_id, :dashboard_id)
    end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_form.html.erb
<%= form_for(@dashboard) do |f| %>
  <% if @dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% @dashboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboards/edit.html.erb
<div class="dashboard_flexbox_container">
  <div class="user_form">

<h1>Editing Dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

</div>
</div>

app/views/dashboards/index.html.erb
<% @user = current_user %>

<div class="dashboard_flexbox_container">
  <div class="dash-flex-child">
    <div id="title">
      <h1 class="hello">Hello <%= @user.name %>!</h1>
    </div>
    <div id="dashboard_list">
      <h3>Owned Dashboards</h3>
      <% @dashboards.each do |dashboard| %>
      <% if @user.id == dashboard.user_id %>



      <div class="standard-button change-color radius">
        <h2><%= link_to dashboard.title, dashboard %></h2>
        <div id="dashboard_links">

          <%= link_to 'Edit', edit_dashboard_path(dashboard) %>
          |
          <%= link_to 'Delete', dashboard, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>


      </br>
    </div>
    <br>
    <br>
    <br>
      <% end %>
    <% end %>
    <div id="dashboard_link_center">
      <%= link_to 'New Dashboard', new_dashboard_path %>
    </div>
  </div>

  <div id="dashboard_list">
    <h3>Joined Dashboards</h3>
    <% @dashboards.each do |dashboard| %>
      <% dashboard.dashboard_memberships.each do |x| %>
        <% if x.member_id == @user.id %>

    <div class="standard-button change-color radius">
      <h4><%= link_to dashboard.title, dashboard %></h4>
    </div>
        <% end %>
    <% end %>
  <% end %>
</div>

  <div id="dashboard_join">
    <h3>Join a Dashboard</h3>
    <%= form_tag(dashboards_search_path, id: "search-form") do %>
    <%= text_field_tag :search, params[:g], placeholder: "Enter Dashboard Code" %>
    <%= submit_tag "Search" %>
    <% end %>
  </div>
</div>
</div>
<br>

app/views/dashboards/join.html.erb
<h1>Join Dashboard</h1>

app/views/dashboards/new.html.erb
<div class="dashboard_flexbox_container">
  <div class="user_form">
    <h1>New Dashboard</h1>

    <%= render 'form' %>

    <%= link_to 'Back', dashboards_path, class:"back_link_nd"%>
  </div>
</div>

app/views/dashboards/show.html.erb
<div class="dashboard_name"><h3><%= @dashboard.title %></h3></div>

<!-- XXXXXXXXXX - Calendar Section XXXXXXXXXXXXX -->

<div id="main">

  <article>
    <div class="center_new_event">
    <% if current_user.id == @dashboard.user_id %>
    <%= link_to 'New Event', new_dashboard_event_path(@dashboard.id), class: "white_links" %>
    <% end %>
  </div>

    <div class="div_cal">
      <div class="calendar_title">
        <div class="well controls">

          <div class="inline_calendar">
          <div class="cal_title">
          <%= link_to calendar_path(date: @date - 1.month) do %>
            <i class="fa fa-arrow-left"></i>
          <% end %>
        </div>
        <div class="cal_title">
          <div class="calendar_month"><%= "#{@date.strftime("%B")} #{@date.year}" %></div>
        </div>
        <div class="cal_title">
          <%= link_to calendar_path(date: @date + 1.month) do %>
            <i class="fa fa-arrow-right"></i>
          <% end %>
        </div>
        </div>
        </div>
      </div>
    </div>

    <div>
      <div>
        <%= calendar @date do |date| %>
          <%= date.day %>
          <% if @events_by_date[date] %>

              <% @events_by_date[date].each do |event| %>
                <%= link_to image_tag("calendar.png", class: "calendar_icon"), event %>

              <% end %>

          <% end %>
        <% end %>
      </div>
    </div>

  </article>

<!-- XXXXXXXXXX - News Feed Dashboard Section XXXXXXXXXXXXX -->

<aside>
  <div class="main_child">
    <h3>Latest Announcements</h3>
        <% if @last_three != nil %>
          <% @last_three.each do |news_feed| %>
            <div class="each_news_event">
                <strong><%= link_to news_feed.title, news_feed %> </strong>
                <br>
                <br>
                <%= news_feed.body.truncate(60) %>
                <br>

              <% if current_user.id == @dashboard.user_id %>
              <%= link_to 'Edit', edit_dashboard_news_feed_path(news_feed.dashboard_id, news_feed) %>
              <%= link_to 'Destroy', news_feed, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>


            </div>
            <br>
          <% end %>
        <% end %>
          <% if current_user.id == @dashboard.user_id %>
        <%= link_to 'New Announcement', new_dashboard_news_feed_path(@dashboard.id), class: "white_links" %>
        <% end %>
  </div>
  </aside>

</div>







  <div id="dashboard_bottom_row">
      <div class="chat">
    <div id="tlkio" data-channel="dashboard" style="width:1000px;height:400px;"></div><script async src="http://tlk.io/embed.js" type="text/javascript"></script>
      </div>

    <div class="docs">
      <div class="docs_child">
        <i class="fa fa-file-text-o fa-5x"></i>
        <br>
        <br>
        <%= link_to 'View Documents', dashboard_uploads_path(@dashboard.id), class: "white_links" %>
        <br>
        <br>
        <% if current_user.id == @dashboard.user_id %>
        <%= form_tag uploads_path, enctype: 'multipart/form-data' do %>
            <%= hidden_field_tag :dashboard_id, "#{@dashboard.id}" %>
            <% if current_user.id == @dashboard.user_id %>

            <%= file_field_tag :file  %>
            <%= submit_tag 'Upload file' %>
            <%end %>
        <% end %>


        <% end %>
      </div>
    </div>
  </div>