config/routes.rb
Rails.application.routes.draw do
  get 'calendar/show'

  get 'uploads/new'
  get 'uploads/create'
  get 'uploads/index'
  get 'dashboards/join'
  put 'dashboards/join'
  post 'dashboards/search'

  resources :uploads
  resources :events
  resources :news_feeds

  resources :dashboards do
    resources :news_feeds
    resources :events
  end

  resources :dashboards, shallow: true do
    resources :uploads
  end

  devise_for :users
  resource :users
  resource :calendar, only: [:show], controller: :calendar
  root 'user#home'

  get "/wyncode" => redirect("http://wyncode.co/")
  get "/about" => 'user#about'


end

app/models/news_feed.rb
class NewsFeed < ActiveRecord::Base
  belongs_to :dashboard
  validates :dashboard_id, presence: true

  def self.items_for_dashboard(dashboard)
    order("created_at DESC").limit(3).where(dashboard_id: dashboard.id)
  end

end

app/controllers/news_feeds_controller.rb
class NewsFeedsController < ApplicationController
  before_action :set_news_feed, only: [:show, :edit, :update, :destroy]
  before_action :set_dashboard, only: [:new, :index]
  before_action :set_twilio_client, only: [:create]
  before_action :authenticate_user!


  # GET /news_feeds
  # GET /news_feeds.json
  def index
    @news_feeds = @dashboard.news_feeds
  end

  # GET /news_feeds/1
  # GET /news_feeds/1.json
  def show
  end

  # GET /news_feeds/new
  def new
    @news_feed = NewsFeed.new
  end

  # GET /news_feeds/1/edit
  def edit
  end

  # POST /news_feeds
  # POST /news_feeds.json
  def create
    # render plain: params.to_json

    @news_feed = NewsFeed.new(news_feed_params)
    @news_feed.dashboard_id = @news_feed[:dashboard_id]

    respond_to do |format|
      if @news_feed.save
        # Twilio
        @dashboard = Dashboard.find(params[:news_feed][:dashboard_id])
        @dashboard.members.each do |member|
          if member.phone_number != nil
            message = @client.account.messages.create(:body => "A new message has been posted in #{@dashboard.title}: Title: #{@news_feed.title} Announcement: #{@news_feed.body.truncate(140)}",
            :to => "+1#{member.phone_number}",
            :from => "+17548006045",
            )
          end
        end
        # Twilio End
        format.html { redirect_to @news_feed, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @news_feed }
      else
        format.html { render :new }
        format.json { render json: @news_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_feeds/1
  # PATCH/PUT /news_feeds/1.json
  def update
    respond_to do |format|
      if @news_feed.update(news_feed_params)
        format.html { redirect_to @news_feed, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_feed }
      else
        format.html { render :edit }
        format.json { render json: @news_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_feeds/1
  # DELETE /news_feeds/1.json
  def destroy
    @news_feed.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_path(@news_feed.dashboard), notice: 'News feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_news_feed
        @news_feed = NewsFeed.find(params[:id])
    end

    def set_dashboard
        @dashboard = Dashboard.find(params[:dashboard_id])
    end

    def set_twilio_client
      @client = Twilio::REST::Client.new ENV["TWILIO_ACCOUNT_SID"], ENV["TWILIO_AUTH_TOKEN"]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_feed_params
      params.require(:news_feed).permit(:title, :body, :dashboard_id)
    end

end

app/helpers/news_feeds_helper.rb
module NewsFeedsHelper
end

app/views/news_feeds/_form.html.erb
<%= form_for(@news_feed) do |f| %>
  <% if @news_feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_feed.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @news_feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.text_field :title, placeholder: "Title" %>
  </div>

  <div class="field">
    <br>
    <%= f.text_area :body, class:"text_area_field", placeholder: "Body" %>
  </div>

  <%= f.hidden_field :dashboard_id, value: params[:dashboard_id] %>



  <div class="actions">
    <%= f.submit "Create Announcement" %>
  </div>
<% end %>
</div>
</div>

app/views/news_feeds/edit.html.erb
<h1>Edit Announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_feed %> |
<%= link_to 'Back', dashboard_path(@news_feed.dashboard) %>

app/views/news_feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing News Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Dashboard</th>
      <th>Dashboard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news_feeds.each do |news_feed| %>
      <tr>
        <td><%= news_feed.title %></td>
        <td><%= news_feed.body %></td>
        <td><%= news_feed.dashboard_id %></td>
        <td><%= news_feed.dashboard %></td>
        <td><%= link_to 'Show', news_feed %></td>
          <td><%= link_to 'Edit', edit_news_feed_path(news_feed) %></td>
          <td><%= link_to 'Destroy', news_feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Announcement', new_news_feed_path %>

<%= link_to 'Dashboard', dashboards_path %>

app/views/news_feeds/new.html.erb
<div class="form_flexbox_container">
  <div class="user_form_wide">

    <h1>New Announcement</h1>
    <%= render 'form' %>

</div>
</div>

app/views/news_feeds/show.html.erb
<div class="form_flexbox_container">
  <div class="show_form">
<p id="notice"><%= notice %></p>


<h3>Title: <%= @news_feed.title %></h3>

<p><%= @news_feed.body %></p>

<h5>Dashboard: <%= @news_feed.dashboard.title %></h5>


<%= link_to 'Edit', edit_news_feed_path(@news_feed) %> |
<%= link_to 'Back', dashboard_path(@news_feed.dashboard) %>
</div>
</div>